### ISSUE TITLE
Stop using flex for sidebar 

### ISSUE THREAD

**Issue by montyanderson** [montyanderson/music-nft-app#4]
I genuinely don't understand what's happening here.

![image](https://user-images.githubusercontent.com/3048503/110737297-08532680-8225-11eb-98a3-9aba10bbd3d3.png)

**Comment by OliverRedman** [comment]
Fixed issue without removing flexbox in commit [https://github.com/montyanderson/music-nft-app/commit/82278d2e5348227dfb6984855d63ebbb52d77138](url)
